const IMAGE_BASEURL = './assets/images';
const DEFAULT_CANVAS_WIDTH = 800;
const DEFAULT_CANVAS_HEIGHT = 600;

const ROTATION_DURATION = 10; // ms
const DEFAULT_ROTATION_SPEED = 0.001;

export {
  IMAGE_BASEURL,
  DEFAULT_CANVAS_WIDTH,
  DEFAULT_CANVAS_HEIGHT,
  ROTATION_DURATION,
  DEFAULT_ROTATION_SPEED,
};
